# Generated by Django 3.0.6 on 2020-06-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
