# Generated by Django 3.0.6 on 2020-06-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('first', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Service.Parent_Type'),
        ),
    ]
