# Generated by Django 3.0.6 on 2020-06-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
