# Generated by Django 3.0.6 on 2020-06-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0003_auto_20200619_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
