# Generated by Django 3.0.6 on 2020-05-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_help_helper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='name',
            new_name='type',
        ),
    ]
