# Generated by Django 3.0.6 on 2020-05-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200529_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='client',
        ),
    ]
