# Generated by Django 3.0.6 on 2020-05-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_request_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Lawyer'),
        ),
    ]
