# Generated by Django 3.0.6 on 2020-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200608_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='first',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
