# Generated by Django 3.0.6 on 2020-06-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_help_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='first',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
