# Generated by Django 3.0.2 on 2020-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Court', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='fast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='court',
            name='loc',
            field=models.CharField(default='Court', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='name',
            field=models.CharField(default='Court', max_length=30),
            preserve_default=False,
        ),
    ]
