# Generated by Django 3.0.2 on 2020-01-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Court', '0002_auto_20200117_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
