# Generated by Django 3.0.2 on 2020-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Court', '0003_court_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('lasthearing', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('desc', models.FileField(upload_to='cases')),
            ],
        ),
    ]
