# Generated by Django 3.0.2 on 2020-01-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Court', '0004_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='desc',
            field=models.TextField(),
        ),
    ]
