# Generated by Django 3.0.6 on 2020-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200531_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.CharField(choices=[('Facebook', 'fa fa-facebook'), ('Twitter', 'fa fa-twitter'), ('LinkedIn', 'fa fa-linkedin'), ('Pintrest', 'fa fa-pintrest'), ('Snapchat', 'fa fa-snapchat'), ('Youtube', 'fa fa-youtube'), ('Reddit', 'fa fa-reddit-alien'), ('Medium', 'fa fa-medium'), ('Google Plus', 'fa fa-google-plus'), ('Fiddle', 'fa fa-js-fiddle'), ('Github', 'fa fa-github')], default='Facebook', max_length=120),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
