# Generated by Django 3.0.6 on 2020-05-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
