# Generated by Django 3.0.6 on 2020-06-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
