# Generated by Django 3.0.2 on 2020-01-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('sect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.OtherType')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
