# Generated by Django 3.1.6 on 2021-02-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='pics')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('credit', models.CharField(max_length=60)),
            ],
        ),
    ]
