# Generated by Django 3.1.6 on 2021-02-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
