# Generated by Django 3.0.6 on 2020-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200531_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
