# Generated by Django 3.0.6 on 2020-05-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image',
        ),
    ]
