# Generated by Django 3.0.6 on 2020-05-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='color',
        ),
    ]
