# Generated by Django 3.0.6 on 2020-05-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_about_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
