# Generated by Django 3.0.6 on 2020-06-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
