# Generated by Django 3.0.6 on 2020-06-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('hightlight_color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
