# Generated by Django 3.0.6 on 2020-06-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contactus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Help',
        ),
    ]
