# Generated by Django 3.0.6 on 2020-06-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contactus', '0002_delete_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('type_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contactus.Type')),
            ],
        ),
    ]
